version: 0.2

phases:
  # install:
  #   runtime-versions:
  #     java: corretto21
  pre_build:
   commands:
      - curl -LO https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.tar.gz
      - mkdir -p amazon-corretto-21
      - tar -xzf amazon-corretto-21-x64-linux-jdk.tar.gz --strip-components=1 -C ./amazon-corretto-21
      - sudo mv amazon-corretto-21/ /usr/local/
      - export JAVA_HOME=/usr/local/amazon-corretto-21
      - export PATH=$JAVA_HOME/bin:$PATH
      - ls -al
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew clean build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - build/libs/*.jar

cache:
  paths:
    - '/root/.gradle/**/*'
